language: node_js
node_js:
  - "node"
  - "5"
  - "4"
  
sudo: false

os:
  - linux

before_script:
  - npm install -g gulp mocha codeclimate-test-reporter
  
script:
  - gulp build
  - gulp test:coverage
  - codeclimate-test-reporter < coverage/lcov.info
    
#before_install:
#  - if [ $TRAVIS_OS_NAME == "linux" ]; then
#      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
#     sh -e /etc/init.d/xvfb start;
#      sleep 3;
#    fi
#    
#install:
#  - npm install
#    
#script:
#  - npm test --silent