import keymirror from 'keymirror';

export default {
    ACTIVITY_STARTED: 'ACTIVITY_STARTED',
    ACTIVITY_STOPED: 'ACTIVITY_STOPED',
    ACTIVITY_UPDATED: 'ACTIVITY_UPDATED',
    ACTIVITY_DELETED: 'ACTIVITY_DELETED',
    ACTIVITY_CREATED: 'ACTIVITY_CREATED',
    ACTIVITY_DONE: 'ACTIVITY_DONE', 
    ACTIVITY_LIST_UPDATED: 'ACTIVITY_LIST_UPDATED',
    ACTIVITY_FINISHED_LIST_UPDATED: 'ACTIVITY_FINISHED_LIST_UPDATED',       
    ACTIVITY_STATUS: {
        ACTIVE: 'active',
        FINISHED: 'finished',
        DELETED: 'deleted'
    },
    INVALID_ENDTIME: -1
}