// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/vinyl-buffer/vinyl-buffer.d.ts
// Type definitions for vinyl-buffer
// Project: https://github.com/hughsk/vinyl-buffer
// Definitions by: Qubo <https://github.com/tkQubo>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped


declare module "vinyl-buffer" {
    namespace buffer {
        interface Buffer {
            (): NodeJS.ReadWriteStream;
        }
    }

    var buffer: buffer.Buffer;

    export = buffer;
}